version: '1.1.8.0'
services:

  DC1N1:
  
    image: cassandra: 3.11.1

    command: bash -c 'if [ -z "$$(ls -A/var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-

    networks:
      - dc1ring

    volumes:
      - ./n1data:/var/lib/cassandra

    environment:
      - CASSANDRA_CLUSTER_NAME=dev_cluster
      - CASSANDRA_SEEDS=DC1N1

    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160

    ulimits:
      memlock: -1
      mproc: 32768
      nofile: 100000


